const MSG = {
  ANALYZE: 'ANALYZE',
  ANALYZE_RESULT: 'ANALYZE_RESULT',
  ANALYZE_ERROR: 'ANALYZE_ERROR',
  GET_ARTICLE: 'GET_ARTICLE',
  HIGHLIGHT: 'HIGHLIGHT',
  SHOW_LOADING: 'SHOW_LOADING',
  SHOW_RESULT: 'SHOW_RESULT',
  SHOW_ERROR: 'SHOW_ERROR',
};
